services:
  blog-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'      
    depends_on:
      - mongo-db
    networks:
      - blog-network

  mongo-db:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge